# Holds DAP config info for apps in all namespaces
# Access is gained via rolebinding to a clusterrole
apiVersion: v1
kind: ConfigMap
metadata:
  name: dap-config
data:
  CONJUR_ACCOUNT: dev
  CONJUR_MASTER_HOST_NAME: conjur-master-mac
  CONJUR_MASTER_PORT: "1443"
  CONJUR_MASTER_URL: https://conjur-master-mac:1443
  CLUSTER_AUTHN_ID: wfpoc
  CONJUR_VERSION: "5"
  CONJUR_APPLIANCE_URL: https://conjur-follower.cyberark.svc.cluster.local
  CONJUR_AUTHN_URL: https://conjur-follower.cyberark.svc.cluster.local/api/authn-k8s/wfpoc
  CONJUR_AUTHN_TOKEN_FILE: /run/conjur/access-token
  CONJUR_MASTER_CERTIFICATE: | 
    -----BEGIN CERTIFICATE-----
    MIIDWTCCAkGgAwIBAgIUR9zJpvvPD/DUpf0sIVucmqCaaOQwDQYJKoZIhvcNAQEL
    BQAwPjEMMAoGA1UECgwDZGV2MRIwEAYDVQQLDAlDb25qdXIgQ0ExGjAYBgNVBAMM
    EWNvbmp1ci1tYXN0ZXItbWFjMB4XDTIwMTEzMDAwMzM0OVoXDTMwMTEyODAwMzM0
    OVowHDEaMBgGA1UEAwwRY29uanVyLW1hc3Rlci1tYWMwggEiMA0GCSqGSIb3DQEB
    AQUAA4IBDwAwggEKAoIBAQDF6eU/9k4uCqbnXjYvVXBBUjYf+1iX89Gbedv+Dp1+
    wAxB8IXzO+H4aJmV5ZwOZHCkXWlxsIEuP57AEBpt8lfKwlE0Kn1AGZ+qEyjTvs82
    WIG1C4tsbCvyAAS4kKXjW+wPFR4BRvjklyb5xjsTBDDCN0ZIwUkmTpxi/dSy7SI6
    6Yp05yBkPkvRHdBbQP/p+sdmUqu1oe3SN667vLzz/DPQ/rPCYYCN71OHYPu3FBkA
    fxZOFqkwXe2phDDDFAR0ni+ukiKLODhL9H8S58UFl83patppb5byr0oOx9p4IIms
    5OUfb1YHjXjNZVI7+S7H1chbVuxpj41kt2GlAD9L8LOpAgMBAAGjcTBvMA4GA1Ud
    DwEB/wQEAwIFoDAdBgNVHQ4EFgQU2jmj7l5rSw0yVb/vlWAYkK/YBwkwPgYDVR0R
    BDcwNYIRY29uanVyLW1hc3Rlci1tYWOCEWNvbmp1ci1tYXN0ZXItbWFjgg1jb25q
    dXItbWFzdGVyMA0GCSqGSIb3DQEBCwUAA4IBAQAQKKyio4qUeWOnCIdYqg4JvWh3
    2qPCaWwMA0PfLV1AStHG96COHrUfWSvWTPkhFwdJJTB6x0/mLmyd2IP7msa6sh15
    Zn6oc7ng6+ODxRZRAfPyqE4X0O/GPBU5GDmJbQzCwZeUp2i+X06RviuaqeY4+dV9
    6eQ0C1ZxF3YJLUQ47wU1DcNQbtMxf4mQEEnr9OIzZv/3xQQU0/C/rn6VJO7j+ME8
    7LuPU9VJ/cJTThWR8qAiTbNTNhQtQQDaa2Pjyfk5ZS5+W4vib41sW5/xhD9ib4fv
    EPbqABv/IGlJ9VbCFwCxAKN1UoWSsVMNIIG9ICH/lQdgk5KysK7kjL4YGfmF
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDnjCCAoagAwIBAgIJANeJamRa0DJ8MA0GCSqGSIb3DQEBCwUAMD4xDDAKBgNV
    BAoMA2RldjESMBAGA1UECwwJQ29uanVyIENBMRowGAYDVQQDDBFjb25qdXItbWFz
    dGVyLW1hYzAeFw0yMDExMzAwMDMzNDVaFw0zMDExMjgwMDMzNDVaMD4xDDAKBgNV
    BAoMA2RldjESMBAGA1UECwwJQ29uanVyIENBMRowGAYDVQQDDBFjb25qdXItbWFz
    dGVyLW1hYzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMU0bD+pNlem
    r0yfw7FPaayv7uL0JhT1lxNiOwF5BuhcrScxj4iJGt99yyg89P3S8HUtWBzoYFya
    CtecrPRejQBQNRPhQwm9KN5TNP4Cd9c94cDKBK3mifz3gIE4kiNwfIoE9W0PzeC4
    U4kOmjouSMdCzhK0+LJQvBii18a6fmAGMNbg2eDYVKJaVAeL/psqlBvZJv0DkJVh
    oLg+fK3W3YXW5yeqR4OwXZy+If4YPYLEbUDcfnHD3Mn8ZJnXSaRQtb4IpOPyDqzp
    +Z0Act7fAoAsIljb3Hid5xBP0zOk6NSJMLS9pQVvn2QCe83vvT5uiP6o4O+iHhEZ
    QNkzEvG9Ze8CAwEAAaOBnjCBmzA+BgNVHREENzA1ghFjb25qdXItbWFzdGVyLW1h
    Y4IRY29uanVyLW1hc3Rlci1tYWOCDWNvbmp1ci1tYXN0ZXIwHQYDVR0OBBYEFBN6
    bihEeOqXJQ65+jOHU5dSAxz1MB8GA1UdIwQYMBaAFBN6bihEeOqXJQ65+jOHU5dS
    Axz1MAwGA1UdEwQFMAMBAf8wCwYDVR0PBAQDAgHmMA0GCSqGSIb3DQEBCwUAA4IB
    AQArlxRBwdi6e3zWRotBGQYTrdAfjLp+Oe8niUy2nD8gr340Tbwg2dPUpMw0L2fF
    QUYNbaekrtldiXSJM0Gsyc4sfaGeMlwQj3WJb8VzrqqNYjxwvWmEG3h5AiSdOIW3
    EiNA47BV8IJnalHiSmb+Fag8IwO0vEHzsfy1LqazPK45+WiJqY652pQ8tNOR3Cds
    vzTUVC2BzA2NyRbl8WvqojOLhqFqidw8WgnuW42mSgQzjoJV/RcOkZJnPs24DIaW
    sU/C9iDHIMhqetIpsN1XLtQwOKnAIbtykKOXrR9teofKwVibIEheOTHKePBkepyB
    ymJrVeM4/or/5keBF64fY8Va
    -----END CERTIFICATE-----
  CONJUR_FOLLOWER_CERTIFICATE: | 
    -----BEGIN CERTIFICATE-----
    MIIDdDCCAlygAwIBAgIUX1UXnZAt8JFq74hmHUeUlxuFCNcwDQYJKoZIhvcNAQEL
    BQAwPjEMMAoGA1UECgwDZGV2MRIwEAYDVQQLDAlDb25qdXIgQ0ExGjAYBgNVBAMM
    EWNvbmp1ci1tYXN0ZXItbWFjMB4XDTIwMTEzMDAwMzQyMVoXDTMwMTEyODAwMzQy
    MVowGjEYMBYGA1UEAwwPY29uanVyLWZvbGxvd2VyMIIBIjANBgkqhkiG9w0BAQEF
    AAOCAQ8AMIIBCgKCAQEAwNjW4yrlP2En+dsb6CTMrqH9astTVMxnxLIln10OMFrW
    eC/bq33c3UfPWXF5RBqt4uzov0w2PrOoA52WrMZjhGqNp0H5ZJX3VHFfcPNT9AnB
    t0JmSTHizPfFxLlYdZzg8zzDmOdP2PV305ZmCpEsONIt0l3wAbV+aHPPolJ08i8w
    bwjoSOgFMnMMg5oi2SW/SSwSOwKKUC8h9aoZPl0rnyCYI17REs0TghRaAzu+OjQt
    rLxJz2ZCVa3NJCeV3RGyjAUY1orSgwr4doRu9BiZ1DZJwRi9jQjxQ8s+5ndhzHyP
    cV6SpxrMpjKtcHYuhA+YvnPE5mRQ/jtXoF1I8EWKxwIDAQABo4GNMIGKMA4GA1Ud
    DwEB/wQEAwIFoDAdBgNVHQ4EFgQU2jmj7l5rSw0yVb/vlWAYkK/YBwkwWQYDVR0R
    BFIwUIIPY29uanVyLWZvbGxvd2VyghFjb25qdXItbWFzdGVyLW1hY4IqY29uanVy
    LWZvbGxvd2VyLmN5YmVyYXJrLnN2Yy5jbHVzdGVyLmxvY2FsMA0GCSqGSIb3DQEB
    CwUAA4IBAQB0+V3NAOmUHcS/mExv+2WP6HMDsJ0SyooSuM8TEpOw39EstP6VWkzY
    DFTn4BjhkFQX/OZ/D+jvyc8baMhOny17zx9uv70KZxB7PvupNA2uz9N9tj5zoCL6
    1SeoHw7WgXJL76oqarb0lNgyPJQaomiwX+VeYkPo90xwre+RmquFgUG6Lav4XLHK
    WmIFY8HTskXRpsUY5x6MUEORVoQ7tRjxO+7QfhMMYeThZY0wCoW34wn/EdRRk6yz
    VNm8TyazC8HUwTdiF0P7SFh0wrH8HKjsM7jDgdPTEhqXGuTL+Fm6/4mDKKqDZyt0
    XYXASHb8sInRygxmVVgr9tJhZrtkoQ3t
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDnjCCAoagAwIBAgIJANeJamRa0DJ8MA0GCSqGSIb3DQEBCwUAMD4xDDAKBgNV
    BAoMA2RldjESMBAGA1UECwwJQ29uanVyIENBMRowGAYDVQQDDBFjb25qdXItbWFz
    dGVyLW1hYzAeFw0yMDExMzAwMDMzNDVaFw0zMDExMjgwMDMzNDVaMD4xDDAKBgNV
    BAoMA2RldjESMBAGA1UECwwJQ29uanVyIENBMRowGAYDVQQDDBFjb25qdXItbWFz
    dGVyLW1hYzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMU0bD+pNlem
    r0yfw7FPaayv7uL0JhT1lxNiOwF5BuhcrScxj4iJGt99yyg89P3S8HUtWBzoYFya
    CtecrPRejQBQNRPhQwm9KN5TNP4Cd9c94cDKBK3mifz3gIE4kiNwfIoE9W0PzeC4
    U4kOmjouSMdCzhK0+LJQvBii18a6fmAGMNbg2eDYVKJaVAeL/psqlBvZJv0DkJVh
    oLg+fK3W3YXW5yeqR4OwXZy+If4YPYLEbUDcfnHD3Mn8ZJnXSaRQtb4IpOPyDqzp
    +Z0Act7fAoAsIljb3Hid5xBP0zOk6NSJMLS9pQVvn2QCe83vvT5uiP6o4O+iHhEZ
    QNkzEvG9Ze8CAwEAAaOBnjCBmzA+BgNVHREENzA1ghFjb25qdXItbWFzdGVyLW1h
    Y4IRY29uanVyLW1hc3Rlci1tYWOCDWNvbmp1ci1tYXN0ZXIwHQYDVR0OBBYEFBN6
    bihEeOqXJQ65+jOHU5dSAxz1MB8GA1UdIwQYMBaAFBN6bihEeOqXJQ65+jOHU5dS
    Axz1MAwGA1UdEwQFMAMBAf8wCwYDVR0PBAQDAgHmMA0GCSqGSIb3DQEBCwUAA4IB
    AQArlxRBwdi6e3zWRotBGQYTrdAfjLp+Oe8niUy2nD8gr340Tbwg2dPUpMw0L2fF
    QUYNbaekrtldiXSJM0Gsyc4sfaGeMlwQj3WJb8VzrqqNYjxwvWmEG3h5AiSdOIW3
    EiNA47BV8IJnalHiSmb+Fag8IwO0vEHzsfy1LqazPK45+WiJqY652pQ8tNOR3Cds
    vzTUVC2BzA2NyRbl8WvqojOLhqFqidw8WgnuW42mSgQzjoJV/RcOkZJnPs24DIaW
    sU/C9iDHIMhqetIpsN1XLtQwOKnAIbtykKOXrR9teofKwVibIEheOTHKePBkepyB
    ymJrVeM4/or/5keBF64fY8Va
    -----END CERTIFICATE-----
